title: Static Generator Options
extends@:
  type: default
  context: blueprints://pages

form:
  fields:
    tabs:
      type: tabs
      fields:
        options:
          type: tab
          fields:
            static_generator:
              type: section
              title: PLUGIN_STATIC_GENERATOR.ADMIN.TITLE
              underline: true
              fields:
                header.search:
                  type: select
                  id: static-generator-search-files-select
                  label: PLUGIN_STATIC_GENERATOR.ADMIN.SEARCH_FILE
                  description: PLUGIN_STATIC_GENERATOR.ADMIN.DESCRIPTION.SEARCH_FILE
                  data-options@:
                    ['\Grav\Plugin\StaticGenerator::getSearchFiles', "index"]
